# update-build-number.ps1
# Actualiza BuildInfo.cs en todos los proyectos con el timestamp actual
# Formato: YYYYMMDDHHMI

param(
    [string]$Version = "1.0.0"
)

$buildNumber = (Get-Date).ToString("yyyyMMddHHmm")
$fullVersion = "$Version-$buildNumber"

Write-Host "Build Number: $buildNumber"
Write-Host "Full Version: $fullVersion"

$root = Split-Path $PSScriptRoot -Parent

# --- 1. Global.Datos (shared by Fichador + Administrador) ---
$globalDatosPath = Join-Path $root "Common\Global.Datos\BuildInfo.cs"
@"
// Auto-generated by update-build-number.ps1 — do not edit manually
namespace Global.Datos
{
    public static class BuildInfo
    {
        public const string BuildNumber = "$buildNumber";
        public const string Version = "$Version";
        public const string FullVersion = Version + "-" + BuildNumber;
    }
}
"@ | Set-Content -Path $globalDatosPath -Encoding UTF8
Write-Host "Updated: $globalDatosPath"

# --- 2. Portal Multi-Tenant ---
$portalMTPath = Join-Path $root "PortalMultiTenant\src\DigitalPlusMultiTenant.Web\BuildInfo.cs"
@"
// Auto-generated by update-build-number.ps1 — do not edit manually
namespace DigitalPlusMultiTenant.Web;

public static class BuildInfo
{
    public const string BuildNumber = "$buildNumber";
    public const string Version = "$Version";
    public const string FullVersion = Version + "-" + BuildNumber;
}
"@ | Set-Content -Path $portalMTPath -Encoding UTF8
Write-Host "Updated: $portalMTPath"

# --- 3. Portal Licencias ---
$portalLicPath = Join-Path $root "PortalLicencias\DigitalPlus.Licencias\BuildInfo.cs"
@"
// Auto-generated by update-build-number.ps1 — do not edit manually
namespace DigitalPlus.Licencias;

public static class BuildInfo
{
    public const string BuildNumber = "$buildNumber";
    public const string Version = "$Version";
    public const string FullVersion = Version + "-" + BuildNumber;
}
"@ | Set-Content -Path $portalLicPath -Encoding UTF8
Write-Host "Updated: $portalLicPath"

# --- 4. Instalador Liviano (actualizar #define AppVersion) ---
$issPath = Join-Path $root "Instaladores\InstaladorLiviano\setup-liviano.iss"
$issContent = Get-Content $issPath -Raw -Encoding UTF8
$issContent = $issContent -replace '#define AppVersion\s+"[^"]+"', "#define AppVersion    `"$fullVersion`""
Set-Content -Path $issPath -Value $issContent -Encoding UTF8 -NoNewline
Write-Host "Updated: $issPath"

Write-Host ""
Write-Host "All build numbers updated to: $fullVersion" -ForegroundColor Green
